'use client';
import React from 'react';
import * as LucideIcons from 'lucide-react';

// Create a mapping of clean icon names to Lucide components
const iconMapping: Record<string, React.ComponentType<any>> = {
  // COMMUNICATION (35)
  Mail: LucideIcons.Mail,
  Speech: LucideIcons.Speech,
  MailOpen: LucideIcons.MailOpen,
  Minimize: LucideIcons.Minimize,
  Minimize2: LucideIcons.Minimize2,
  Maximize: LucideIcons.Maximize,
  Maximize2: LucideIcons.Maximize2,
  Inbox: LucideIcons.Inbox,
  Send: LucideIcons.Send,
  MessageCircle: LucideIcons.MessageCircle,
  MessageSquare: LucideIcons.MessageSquare,
  Smartphone: LucideIcons.Smartphone,
  Phone: LucideIcons.Phone,
  PhoneCall: LucideIcons.PhoneCall,
  PhoneForwarded: LucideIcons.PhoneForwarded,
  PhoneIncoming: LucideIcons.PhoneIncoming,
  PhoneOutgoing: LucideIcons.PhoneOutgoing,
  PhoneOff: LucideIcons.PhoneOff,
  Video: LucideIcons.Video,
  VideoOff: LucideIcons.VideoOff,
  Mic: LucideIcons.Mic,
  MicOff: LucideIcons.MicOff,
  Headphones: LucideIcons.Headphones,
  Rss: LucideIcons.Rss,
  AtSign: LucideIcons.AtSign,
  Hash: LucideIcons.Hash,
  Voicemail: LucideIcons.Voicemail,
  Share: LucideIcons.Share,
  Paperclip: LucideIcons.Paperclip,
  Camera: LucideIcons.Camera,
  CameraOff: LucideIcons.CameraOff,
  Speaker: LucideIcons.Speaker,
  Bluetooth: LucideIcons.Bluetooth,
  Radio: LucideIcons.Radio,
  RadioTower: LucideIcons.RadioTower,
  RadioReceiver: LucideIcons.RadioReceiver,
  Settings: LucideIcons.Settings,
  Server: LucideIcons.Server,
  Ruler: LucideIcons.Ruler,
  Podcast: LucideIcons.Podcast,
  Users: LucideIcons.Users,
  Weight: LucideIcons.Weight,
  CircleDashed: LucideIcons.CircleDashed,
  Crosshair: LucideIcons.Crosshair,
  Ear: LucideIcons.Ear,
  EarOff: LucideIcons.EarOff,
  MessageSquareText: LucideIcons.MessageSquareText,
  MessageSquarePlus: LucideIcons.MessageSquarePlus,

  // SERVERS & INFRASTRUCTURE (35)
  Cpu: LucideIcons.Cpu,
  Database: LucideIcons.Database,
  HardDrive: LucideIcons.HardDrive,
  HardDriveUp: LucideIcons.HardDriveUpload,
  Cloud: LucideIcons.Cloud,
  CloudRain: LucideIcons.CloudRain,
  CloudLightning: LucideIcons.CloudLightning,
  CloudDrizzle: LucideIcons.CloudDrizzle,
  CloudSnow: LucideIcons.CloudSnow,
  Archive: LucideIcons.Archive,
  Package: LucideIcons.Package,
  Key: LucideIcons.Key,
  Lock: LucideIcons.Lock,
  Unlock: LucideIcons.Unlock,
  Shield: LucideIcons.Shield,
  ShieldOff: LucideIcons.ShieldOff,
  Terminal: LucideIcons.Terminal,
  Wifi: LucideIcons.Wifi,
  WifiOff: LucideIcons.WifiOff,
  Activity: LucideIcons.Activity,
  Monitor: LucideIcons.Monitor,
  Battery: LucideIcons.Battery,
  Calendar: LucideIcons.CalendarCheck,
  BatteryFull: LucideIcons.BatteryFull,
  BatteryCharging: LucideIcons.BatteryCharging,
  Blocks: LucideIcons.Blocks,
  Power: LucideIcons.Power,
  Wrench: LucideIcons.Wrench,
  Cog: LucideIcons.Cog,
  MemoryStick: LucideIcons.MemoryStick,
  Layers: LucideIcons.Layers,
  Grid: LucideIcons.Grid,
  Code: LucideIcons.Code,
  Binary: LucideIcons.Binary,
  Zap: LucideIcons.Zap,
  Plug: LucideIcons.Plug,
  Router: LucideIcons.Router,
  Fold: LucideIcons.FoldHorizontal,

  // USER EXPERIENCE & INTERFACE (40)
  Search: LucideIcons.Search,
  Filter: LucideIcons.Filter,
  SmartphoneNFC: LucideIcons.SmartphoneNfc,
  Charge: LucideIcons.SmartphoneCharging,
  Sliders: LucideIcons.Sliders,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  Loader: LucideIcons.Loader,
  Check: LucideIcons.Check,
  CheckCircle: LucideIcons.CheckCircle,
  CheckSquare: LucideIcons.CheckSquare,
  Plus: LucideIcons.Plus,
  PlusCircle: LucideIcons.PlusCircle,
  PlusSquare: LucideIcons.PlusSquare,
  Minus: LucideIcons.Minus,
  MinusCircle: LucideIcons.MinusCircle,
  MinusSquare: LucideIcons.MinusSquare,
  Trash: LucideIcons.Trash,
  Trash2: LucideIcons.Trash2,
  Edit: LucideIcons.Edit,
  Edit2: LucideIcons.Edit2,
  Edit3: LucideIcons.Edit3,
  Save: LucideIcons.Save,
  User: LucideIcons.User,
  MoreHorizontal: LucideIcons.MoreHorizontal,
  MoreVertical: LucideIcons.MoreVertical,
  List: LucideIcons.List,
  Grid2X2: LucideIcons.Grid2X2,
  Menu: LucideIcons.Menu,
  Grip: LucideIcons.Grip,
  Copy: LucideIcons.Copy,
  Clipboard: LucideIcons.Clipboard,
  Download: LucideIcons.Download,
  Upload: LucideIcons.Upload,
  File: LucideIcons.File,
  Folder: LucideIcons.Folder,
  FolderOpen: LucideIcons.FolderOpen,
  Home: LucideIcons.Home,
  Clock: LucideIcons.Clock,
  Timer: LucideIcons.Timer,

  // MARKETING & ANALYTICS (35)
  BarChart: LucideIcons.BarChart,
  BarChart2: LucideIcons.BarChart2,
  BarChart3: LucideIcons.BarChart3,
  PieChart: LucideIcons.PieChart,
  LineChart: LucideIcons.LineChart,
  TrendingUp: LucideIcons.TrendingUp,
  TrendingDown: LucideIcons.TrendingDown,
  DollarSign: LucideIcons.DollarSign,
  CreditCard: LucideIcons.CreditCard,
  ShoppingCart: LucideIcons.ShoppingCart,
  ShoppingBag: LucideIcons.ShoppingBag,
  Gift: LucideIcons.Gift,
  Award: LucideIcons.Award,
  Tag: LucideIcons.Tag,
  Tags: LucideIcons.Tags,
  Percent: LucideIcons.Percent,
  Globe: LucideIcons.Globe,
  Share2: LucideIcons.Share2,
  ExternalLink: LucideIcons.ExternalLink,
  Link: LucideIcons.Link,
  Link2: LucideIcons.Link2,
  Bookmark: LucideIcons.Bookmark,
  BookOpen: LucideIcons.BookOpen,
  Book: LucideIcons.Book,
  ZoomIn: LucideIcons.ZoomIn,
  ZoomOut: LucideIcons.ZoomOut,
  RefreshCw: LucideIcons.RefreshCw,
  FileText: LucideIcons.FileText,
  Target: LucideIcons.Target,
  Megaphone: LucideIcons.Megaphone,
  MousePointer: LucideIcons.MousePointer,
  Presentation: LucideIcons.Presentation,
  Briefcase: LucideIcons.Briefcase,
  Building: LucideIcons.Building,
  Store: LucideIcons.Store,

  // TRANSPORT & NAVIGATION (30)
  Map: LucideIcons.Map,
  Gauge: LucideIcons.Gauge,
  GaugeCircle: LucideIcons.GaugeCircle,
  MapPin: LucideIcons.MapPin,
  Compass: LucideIcons.Compass,
  Navigation: LucideIcons.Navigation,
  Anchor: LucideIcons.Anchor,
  Truck: LucideIcons.Truck,
  Car: LucideIcons.Car,
  Plane: LucideIcons.Plane,
  ArrowUp: LucideIcons.ArrowUp,
  ArrowDown: LucideIcons.ArrowDown,
  ArrowLeft: LucideIcons.ArrowLeft,
  ArrowRight: LucideIcons.ArrowRight,
  ArrowUpCircle: LucideIcons.ArrowUpCircle,
  ArrowDownCircle: LucideIcons.ArrowDownCircle,
  ArrowLeftCircle: LucideIcons.ArrowLeftCircle,
  ArrowRightCircle: LucideIcons.ArrowRightCircle,
  ChevronUp: LucideIcons.ChevronUp,
  ChevronDown: LucideIcons.ChevronDown,
  ChevronLeft: LucideIcons.ChevronLeft,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronsUp: LucideIcons.ChevronsUp,
  ChevronsDown: LucideIcons.ChevronsDown,
  ChevronsLeft: LucideIcons.ChevronsLeft,
  ChevronsRight: LucideIcons.ChevronsRight,
  RotateCcw: LucideIcons.RotateCcw,
  RotateCw: LucideIcons.RotateCw,
  Move: LucideIcons.Move,
  MoveHorizontal: LucideIcons.MoveHorizontal,
  MoveVertical: LucideIcons.MoveVertical,
  Route: LucideIcons.Route,

  // CRITICAL ALERTS & NOTIFICATIONS (25)
  AlertCircle: LucideIcons.AlertCircle,
  AlertTriangle: LucideIcons.AlertTriangle,
  AlertOctagon: LucideIcons.AlertOctagon,
  Bell: LucideIcons.Bell,
  BellOff: LucideIcons.BellOff,
  XCircle: LucideIcons.XCircle,
  XSquare: LucideIcons.XSquare,
  HelpCircle: LucideIcons.HelpCircle,
  Info: LucideIcons.Info,
  Triangle: LucideIcons.Triangle,
  Hexagon: LucideIcons.Hexagon,
  Circle: LucideIcons.Circle,
  Square: LucideIcons.Square,
  Star: LucideIcons.Star,
  PauseCircle: LucideIcons.PauseCircle,
  PlayCircle: LucideIcons.PlayCircle,
  Thermometer: LucideIcons.Thermometer,
  LifeBuoy: LucideIcons.LifeBuoy,
  Volume: LucideIcons.Volume,
  Volume1: LucideIcons.Volume1,
  Volume2: LucideIcons.Volume2,
  VolumeX: LucideIcons.VolumeX,
  Siren: LucideIcons.Siren,
  ShieldCheck: LucideIcons.ShieldCheck,
};

// Export the icon options for forms - generated from the mapping keys
export const ICON_OPTIONS = Object.keys(iconMapping)
  .map(key => ({
    value: key,
    label: key.replace(/([A-Z])/g, ' $1').trim()
  }))
  .sort((a, b) => a.label.localeCompare(b.label));

interface DynamicFeatherIconProps {
  name: string;
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

const DynamicFeatherIcon: React.FC<DynamicFeatherIconProps> = ({ name, ...props }) => {
  const IconComponent = iconMapping[name];

  if (!IconComponent) {
    // Return a default icon if the name is invalid
    return <LucideIcons.HelpCircle {...props} />;
  }

  return <IconComponent {...props} />;
};

export default DynamicFeatherIcon; 